### ISSUE TITLE
--set-num-threads parameter throws error

### ISSUE THREAD

**Issue by brgmn** [speechcatcher-asr/speechcatcher#1]
The following error occures when trying to use the _--set-num-threads_ parameter: 

`RuntimeError: set_num_threads expects an int, but got str`

Besides this I find it strange to use "set" in a commandline option. Maybe we can just skip that and use --num-threads instead. 

**Definition of Done:** 
- [x] The --set-num-threads parameter has been renamed to --num-threads
- [x] The value of --num-threads has been casted to integer by using python's "int()" method

**Additional Information**
I couldn't notice a speed improvement by using 10 Threads (M2 Max). Maybe pytorch just isn't able to use the threads in that environment.

**Comment by bmilde** [comment]
thanks!
