### ISSUE TITLE
Working with VOSK?

### ISSUE THREAD

**Issue by VenominousX** [speechcatcher-asr/speechcatcher#8]
Hi, i want to know if Speechcatcher is compatible with Vosk. There is a link to Speechcatcher on the github kaldi-tuda-de site, which works fine with Vosk.

Thanks in advanced

**Comment by bmilde** [comment]
If you want to use speechcatcher as a vosk compatible websocket server, you can now use the command speechcatcher_server in the most recent version of speechcatcher. For example this would create the server on ws://localhost:2700/:

`speechcatcher_server --vosk-output-format --port 2700`

You can use it as a drop in replacement for the vosk speech server.

**Comment by VenominousX** [comment]
Thank you for your response :)
